### ISSUE TITLE
perlfaq4: =head2 How do I capitalize all the words on one line?

### ISSUE THREAD

**Issue by khwilliamson** [perl-doc-cats/perlfaq#100]
This section uses a quote from Dr. Strangelove, and then slips into the Flintstones and it doesn't make sense to me.   Also, it is out-of-date.  \b{wb} is better than plain \b for finding word breaks and in fact treats an embedded apostrophe as not being a break.  This could be a teaching moment about these newer capabilities of Perl

**Comment by briandfoy** [comment]
Here's the patch file in case this PR loses the diff when I clean up my fork later this month.

[0001-Update-the-sentence-capitalization-for-v5.22-b-wb-10.patch](https://github.com/perl-doc-cats/perlfaq/files/12862151/0001-Update-the-sentence-capitalization-for-v5.22-b-wb-10.patch)
