### ISSUE TITLE
[doc] Issues with perlfaq4

### ISSUE THREAD

**Issue by carlos157oliveira** [perl-doc-cats/perlfaq#101]
## Where

perlfaq4

Link: https://perldoc.perl.org/perlfaq4

## Description

Good afternoon.

I have been reading perlfaq4 and noted some inconsistencies, which could be just my doubts, however I would like to point them out section by section.

### [Why doesn't & work the way I want it to?](https://perldoc.perl.org/perlfaq4#Why-doesn't-&-work-the-way-I-want-it-to?)

The final code sample checks if the result of the bit-wise AND doesn't yield a string with no null bytes, which means that it checks if the result has null bytes. It seems the opposite of the intention.

### [How do I find the day or week of the year?](https://perldoc.perl.org/perlfaq4#How-do-I-find-the-day-or-week-of-the-year?)

It says:

> To get the day of year for any date, use POSIX's mktime to get a time in epoch seconds for the argument to localtime.

but the code sample below it gets the week of the year.

### [How can I expand variables in text strings?](https://perldoc.perl.org/perlfaq4#How-can-I-expand-variables-in-text-strings?)

It says:

> The first /e evaluates $1 on the replacement side and turns it into $foo.

but from my tests, it isn't necessary the /e flag to work with the special variable $1. It is needed only if you are going to put more complex code inside the replacement. I found it nice that the author tried to be didactic to explain the */ee* flag (double-e flag), but it doesn't seem so exactly when talking about the single-e flag */e* in the path towards it.

### [How can I know how many entries are in a hash?](https://perldoc.perl.org/perlfaq4#How-can-I-know-how-many-entries-are-in-a-hash?)

The phrase:

> You can use the keys() built-in function in scalar context to find out have many entries you have in a hash:

seems misspelled. I think the correct one has "how" in the place of the first "have":

> You can use the keys() built-in function in scalar context to find out how many entries you have in a hash:

### [How do I manipulate arrays of bits?](https://perldoc.perl.org/perlfaq4#How-do-I-manipulate-arrays-of-bits?)

Using the first two code samples of this section, I tried to convert a list of integers into a bit vector then back to a list, but it didn't work as I expected. I confess that I don't fully understand the algorithm used for the conversions, maybe there is something I messed up.

## Gratitude

Thank you all for putting together Perl and the documentation. I am so sorry if in my exposing I gave the impression of being too critic. What I really want is to hang out with you guys.

**Comment by briandfoy** [comment]
I'm looking at these and have fixes in #104.

* Why doesn't & work the way I want it to? - I've rewritten this answer. I don't know what Tom was getting at, but even then we have new bitwise features that the answer should mention.
* How do I find the day or week of the year? - fixed typo
* How can I expand variables in text strings? - without the `/ee` you don't get the right output. I think the current answer is correct. Let me know if I'm missing something.
* How can I know how many entries are in a hash? - fixed typo
* How do I manipulate arrays of bits? - I think the answer is correct. Maybe the original poster used numbers that weren't 0 or 1. The `vec` stuff is a bit mind bending until you grok it.

**Comment by carlos157oliveira** [comment]
Hi, so nice to see someone answering me. I think you are famous in the Perl community because I have seen your name several times.

How can I expand variables in text strings? - The double `/ee` part is correct, my suggestion was about the single `/e`. What I was trying to say is that someone doesn't need the `/e` to turn `$1` into `$foo`, it needs only if the replacement is an expression.  And then, if the result of this expression must be `eval`uated, we add a further "e" to become the modifier `/ee`.

**Comment by carlos157oliveira** [comment]
How do I manipulate arrays of bits? - I tried running the following code to test the examples given but I am not getting the array of 0s and 1s back, it returns [ 0, 5, 6 ].

```pl
use strict;
use warnings;
use v5.36;

use Data::Dumper;

sub bitvec_to_list {
    my $vec = shift;
    my @ints;
    # Find null-byte density then select best algorithm
    if ($vec =~ tr/\0// / length $vec > 0.95) {
        use integer;
        my $i;

        # This method is faster with mostly null-bytes
        while($vec =~ /[^\0]/g ) {
            $i = -9 + 8 * pos $vec;
            push @ints, $i if vec($vec, ++$i, 1);
            push @ints, $i if vec($vec, ++$i, 1);
            push @ints, $i if vec($vec, ++$i, 1);
            push @ints, $i if vec($vec, ++$i, 1);
            push @ints, $i if vec($vec, ++$i, 1);
            push @ints, $i if vec($vec, ++$i, 1);
            push @ints, $i if vec($vec, ++$i, 1);
            push @ints, $i if vec($vec, ++$i, 1);
        }
    }
    else {
        # This method is a fast general algorithm
        use integer;
        my $bits = unpack "b*", $vec;
        push @ints, 0 if $bits =~ s/^(\d)// && $1;
        push @ints, pos $bits while($bits =~ /1/g);
    }

    return \@ints;
}

# "a" in ASCII, reversing because of big-endian format ?
my @ints = reverse (0,1,1,0,0,0,0,1);
my $vec = '';
foreach( 0 .. $#ints ) {
    vec($vec,$_,1) = 1 if $ints[$_];
}

say $vec;

say Dumper bitvec_to_list $vec;
```

**Comment by briandfoy** [comment]
> How do I manipulate arrays of bits? - I tried running the following code to test the examples given but I am not getting the array of 0s and 1s back, it returns [ 0, 5, 6 ].

Notice that 0, 5, and 6 are the positions where the bit is set. That's what the subroutines are doing. If you want the list back, 

     my @array = (0) x $length;
     @array[@set] = (1) x @set;

The subroutine in the answer is a bit weird because it's doing some hot-loop optimization. This is not too weird when you are using bit vectors because people usually decide to take on that pain when they really need the improvement.

**Comment by briandfoy** [comment]
I think this issue can now be closed. If there are other problems, new issues (one issue per problem) can be opened.
