### ISSUE TITLE
License not Artistic 2?

### ISSUE THREAD

**Issue by RandalSchwartz** [perl-doc-cats/perlfaq#110]
I'm a bit out of the loop, but hasn't artistic 2 basically superseded any use of artistic 1?

**Comment by Grinnz** [comment]
Pretty much, but for two things: it can be beneficial for distributions closely related to core Perl to share its license, and it is extremely difficult to change the license of an existing project as you need consent of all contributors.

**Comment by haarg** [comment]
Perl core is still dual licensed as Artistic 1 and GPL 1. Most of CPAN also follows this.

**Comment by RandalSchwartz** [comment]
I stand informed.  Thanks.  I'll go back under my rock now... :)
