### ISSUE TITLE
Possible pod issues in perlglossary

### ISSUE THREAD

**Issue by dsteinbrunner** [perl-doc-cats/perlfaq#41]
Looking at these entries and the associated POD makes me thing there is some cleanup needed here but I don't think I would know the best way to clean it up:

progressive matching
Pattern matching matching>that picks up where it left off before.

typed lexical
A lexical variable lexical>that is declared with a class type: my Pony $bill.

**Comment by karenetheridge** [comment]
Closing; we need specific examples to know if/where there is a problem.
