### ISSUE TITLE
Found ~~ in perlfaq4

### ISSUE THREAD

**Issue by andk** [perl-doc-cats/perlfaq#57]
Now that the user gets

``` text
Smartmatch is experimental at -e line 1.
```

would it be the time to remove such examples from perlfaq?

**Comment by karenetheridge** [comment]
yes, IMO we should stop suggesting syntax that is now discouraged elsewhere :)

**Comment by ranguard** [comment]
Yes please - pull request appreciated

**Comment by karenetheridge** [comment]
Merged in #63.
