### ISSUE TITLE
perfaq2 magazine section out-of-date

### ISSUE THREAD

**Issue by epoise** [perl-doc-cats/perlfaq#64]
This is a bug report for perl from eamon.roque@lex-com.net,
generated with the help of perlbug 1.40 running under perl 5.22.1.

---

[Please describe your issue here]

perfaq2 also contains a list of perl magazines. $foo is not being published anymore (back issues are possibly available) and the perl-zeitung address resolves to a generic WebHoster site. The new address is probably http://perl-zeitung.ghit.at/, although it does not seem to be very active.
## [Please do not change anything below this line]

---

Flags:
    category=docs
##     severity=low

Site configuration information for perl 5.22.1:

Configured by ASSI at Wed Mar  9 22:32:00 CET 2016.

Summary of my perl5 (revision 5 version 22 subversion 1) configuration:

  Platform:
    osname=cygwin, osvers=2.5.0(0.29453), archname=cygwin-thread-multi
    uname='cygwin_nt-6.3 cygwin 2.5.0(0.29453) 2016-02-18 14:15 x86_64 cygwin '
    config_args='-d -e -Dprefix=/usr -Dmksymlinks -Darchname=x86_64-cygwin-threads -Dlibperl=cygperl5_22.dll -Dcc=gcc -Dld=g++ -Accflags=-ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/build=/usr/src/debug/perl-5.22.1-2 -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/src/perl-98c63ea=/usr/src/debug/perl-5.22.1-2 -fwrapv'
    hint=previous, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/build=/usr/src/debug/perl-5.22.1-1 -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/src/perl-98c63ea=/usr/src/debug/perl-5.22.1-1 -fwrapv -fno-strict-aliasing -fstack-protector-strong -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/build=/usr/src/debug/perl-5.22.1-2 -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/src/perl-98c63ea=/usr/src/debug/perl-5.22.1-2 -fwrapv',
    optimize='-O3',
    cppflags='-DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/build=/usr/src/debug/perl-5.22.1-1 -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/src/perl-98c63ea=/usr/src/debug/perl-5.22.1-1 -fwrapv -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/build=/usr/src/debug/perl-5.22.1-1 -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/src/perl-98c63ea=/usr/src/debug/perl-5.22.1-1 -fwrapv -fno-strict-aliasing -fstack-protector-strong -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/build=/usr/src/debug/perl-5.22.1-2 -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/src/perl-98c63ea=/usr/src/debug/perl-5.22.1-2 -fwrapv'
    ccversion='', gccversion='5.3.0', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678, doublekind=3
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16, longdblkind=3
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='g++', ldflags =' -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/lib /usr/lib/../lib/../include/w32api /usr/local/lib /lib /usr/lib /usr/lib/../lib/../include/w32api
    libs=-lpthread -ldb -ldl -lcrypt
    perllibs=-lpthread -ldl -lcrypt
    libc=/usr/lib/libc.a, so=dll, useshrplib=true, libperl=cygperl5_22.dll
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags=' --shared  -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -L/usr/local/lib -fstack-protector-strong'

---

@INC for perl 5.22.1:
    /usr/lib/perl5/site_perl/5.22/x86_64-cygwin-threads
    /usr/lib/perl5/site_perl/5.22
    /usr/lib/perl5/vendor_perl/5.22/x86_64-cygwin-threads
    /usr/lib/perl5/vendor_perl/5.22
    /usr/lib/perl5/5.22/x86_64-cygwin-threads
    /usr/lib/perl5/5.22
    .

---

Environment for perl 5.22.1:
    HOME=/home/Eamon.Roque
    LANG=de_DE.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/bin:/usr/bin:/cygdrive/e/Natural-CE/AdabasClient/bin32:/cygdrive/e/Natural-CE/AdabasClient/bin:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Client:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/SafeNet/Authentication/SAC/x64:/cygdrive/c/Program Files/SafeNet/Authentication/SAC/x32:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files/Hercules/R3.11:/cygdrive/e/Go/bin:/cygdrive/c/PROGRA~1/IBM/SQLLIB/BIN:/cygdrive/c/PROGRA~1/IBM/SQLLIB/FUNCTION:/cygdrive/c/rakudo/bin:/cygdrive/c/rakudo/share/perl6/site/bin:/usr/lib/lapack
    PERL_BADLANG (unset)
    SHELL=/bin/bash

**Comment by ranguard** [comment]
We'll have a look when we do another release - thanks

**Comment by briandfoy** [comment]
We can close this issue now.
