### ISSUE TITLE
Add info about Mojolicious

### ISSUE THREAD

**Issue by KES777** [perl-doc-cats/perlfaq#66]
>Where can I learn about CGI or Web programming in Perl?

It will be good to see links in this section to Mojolicious framework

**Comment by davorg** [comment]
This section already talks about £modern Perl web frameworks" and links to Plack on CPAN. We couldn't mention Mojolicious without also mentioning (at least) Catalyst and Dancer as well. And then we run the risk of having another list of resources that can easily get out of date.

**Comment by karenetheridge** [comment]
Agreed. Plack's website already contains a comprehensive list of
frameworks, clients, servers etc built atop the PSGI standard, so it is
sufficient to link to that.

**Comment by KES777** [comment]
>Looking in to Plack and modern ...

If you mean link hehind [Plack](http://search.cpan.org/perldoc/Plack) word. There is no such list.

I will agreed if thank link will be replaced by: http://plackperl.org/

**Comment by davorg** [comment]
That's certainly worth thinking about.
