### ISSUE TITLE
[perl 132693] perlfaq3 and perlfaq9 broken links fixes

### ISSUE THREAD

**Issue by jkeenan** [perl-doc-cats/perlfaq#71]
Below was originally filed at https://rt.perl.org/Ticket/Display.html?id=132693.  Here are links to the patches which the original poster prepared and attached to the ticket:
https://rt.perl.org/Ticket/Attachment/1522568/813557/0001-perlfaq3-broken-links-to-Tom-Christiansen-s-archives.patch
https://rt.perl.org/Ticket/Attachment/1522568/813556/0002-perlfaq3-broken-link-to-Profiling-Perl-article-fixed.patch
https://rt.perl.org/Ticket/Attachment/1522568/813555/0003-perlfaq3-link-to-Vile-updated-301-redirect-for-the-o.patch
https://rt.perl.org/Ticket/Attachment/1522568/813554/0004-perlfaq9-fixed-broken-links-in-examples-tiny-code-up.patch
#####

This is a bug report for perl from dctabuyz@yandex.ru,
generated with the help of perlbug 1.41 running under perl 5.27.8.

-----------------------------------------------------------------
there are some broken links in perlfaq, some of them i've fixed,
some of them are not fixed because it is not clear for me how to do it right

links fixed:

perlfaq3:

	http://www.cpan.org/authors/id/TOMC/scripts/toms.exrc.gz
	http://www.cpan.org/authors/Tom_Christiansen/scripts/rep.gz
	http://www.cpan.org/authors/Tom_Christiansen/scripts/toms.exrc.gz

	http://dickey.his.com/vile/vile.html 

	http://www.perl.com/lpt/a/850

perlfaq9:
	http://www.perl.com/cgi-bin/cpan_mod

links NOT fixed:

http://perl-zeitung.at.tf	     (connection timeout)
http://par.perl.org/		     (NXDOMAIN)
http://www.solutionsoft.com/perl.htm (NXDOMAIN)
http://www.fastcgi.com/ 	     (connection timeout, seems not supported anymore: https://redd.it/4bywjn)

http://web.cse.msu.edu/~cse320/Documents/FloatingPoint.pdf (not found, accessible via webarchive)

**Comment by dctabuyz** [comment]
I think it is related to #7

**Comment by karenetheridge** [comment]
Thank you for this; I will look at it shortly!

**Comment by karenetheridge** [comment]
I have applied these patches. thanks!
