### ISSUE TITLE
Perldoc5: 000,000,000 cultural bias

### ISSUE THREAD

**Issue by jidanni** [perl-doc-cats/perlfaq#88]
On https://github.com/Perl/perl5/issues/17840 we note "3" has cultural bias and should have a note added to make it more general.

**Comment by karenetheridge** [comment]
Please feel free to submit a pull request. Another code example to produce a different style, for example the Indian number grouping, would be useful.

**Comment by jidanni** [comment]
P.S., I emailed the Number::Format author about the same problem.

**Comment by briandfoy** [comment]
Here's the patch for #108, which might disappear when I delete my fork. 

[0001-In-the-commify-answer-drop-Number-Format-for-CLDR-Nu.patch](https://github.com/perl-doc-cats/perlfaq/files/12862139/0001-In-the-commify-answer-drop-Number-Format-for-CLDR-Nu.patch)

**Comment by briandfoy** [comment]
This issue can be closed.

**Comment by jwrightecs** [comment]
Locale::CLDR might be a better choice, as it is up to date (except for dot releases) with CLDR (version 44), while CLDR::Number is still at CLDR v29, updating CLDR::Number to v44 or v44.1 would make the final table in the [referenced article](https://www.olafalders.com/2015/09/04/stop-writing-your-own-commify-functions/) much less surprising (the decimal separator would be consistently `.`)
